INSERT INTO PERSONAS (NOMBRE, APELLIDO, EDAD) VALUES ( 'JUAN', 'PEREZ', 25);
INSERT INTO PERSONAS (NOMBRE, APELLIDO, EDAD) VALUES ( 'JUAN', 'PEREZ', 25);
INSERT INTO PERSONAS (NOMBRE, APELLIDO, EDAD) VALUES ( 'JUAN', 'PEREZ', 25);
INSERT INTO PERSONAS (NOMBRE, APELLIDO, EDAD) VALUES ( 'JUAN', 'PEREZ', 25);
INSERT INTO PERSONAS (NOMBRE, APELLIDO, EDAD) VALUES ( 'JUAN', 'PEREZ', 25);
INSERT INTO PERSONAS (NOMBRE, APELLIDO, EDAD) VALUES ( 'JUAN', 'PEREZ', 25);



